# Generated by Django 2.2.1 on 2019-06-27 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'param',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_team_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'team',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_tournament_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tournament',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_match_id', models.IntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('score_home_team', models.IntegerField(blank=True, null=True)),
                ('score_away_team', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('away_team_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matchs', to='core.Team')),
                ('home_team_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matchs', to='core.Team')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchs', to='core.Tournament')),
            ],
            options={
                'db_table': 'match',
                'ordering': ['tournament'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('period', models.CharField(max_length=255)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('team', models.BooleanField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.Match')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.Param')),
            ],
            options={
                'db_table': 'event',
                'ordering': ['param'],
            },
        ),
    ]
