# Generated by Django 2.2.1 on 2019-07-04 02:27

import betAdmin.payments.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('agency', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=10)),
                ('digit', models.CharField(max_length=2)),
                ('op', models.CharField(max_length=5)),
                ('account_type', models.CharField(choices=[('CC', 'checking account'), ('CP', 'savings account')], default='CP', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payments_administrator_account',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CC', 'credit card'), ('TK', 'ticket'), ('TR', 'transfer'), ('DP', 'deposit')], default='TR', max_length=2)),
                ('is_paid', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=betAdmin.payments.models.Payment.payment_directory_path)),
                ('adm_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_adm_account', to='payments.AdministratorAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
