# Generated by Django 2.2.1 on 2019-07-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratoraccount',
            name='bank_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='administratoraccount',
            name='bank_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
