# Generated by Django 2.2.1 on 2019-07-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20190711_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('day', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'payments_plan',
            },
        ),
    ]
