# Generated by Django 2.2.1 on 2019-07-15 23:44

import betAdmin.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='value',
        ),
        migrations.AlterField(
            model_name='payment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=betAdmin.payments.models.Payment.payment_directory_path),
        ),
    ]
