# Generated by Django 2.2.1 on 2019-07-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
